### ISSUE TITLE
train_and_evaluate.ipynb on MacOs & Visual Studio Code -> setup.py not found

### ISSUE THREAD

**Issue by fbeenaerts** [tensortrade-org/tensortrade#110]
<em>The !pip3 install -e .. - U gives always error: ERROR: File "setup.py" not found. Directory cannot be installed in editable mode

This is when executing the train_and_evaluate.ipynb file under folder \examples
</em>

**System information**

- OS Platform and Distribution: macOS Mojave - 10.14.6
- TensorTrade version: 0.1.0-rc1
- TensorFlow version: 1.13.1
- Python version: 3.6.7

**Comment by rracinskij** [comment]
Same error while trying to build a Docker image or run the code in the Google Colab.

**Comment by Tonza91** [comment]
Did you already solve it?

**Comment by jjbeto** [comment]
On my Mac (macOS Catalina 10.15.2) with Python 3.7.4: **all ipynb files fails to run**

I also notice that lots of the examples actually cannot run on master due to missing constructor parameters. As I'm completely newbie here and the project looks really promissing, I'm trying to track down each error and find how to solve it, but it is really hard to get into the project and just play samples.

Maybe some effort to make a simple and minimum happy flow (running one strategy and evaluate it) would be really helpful for beginners.

**Comment by notadamking** [comment]
Updated the notebook. Should be fixed.
