### ISSUE TITLE
Attribute _value not initialized in class Node

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#166]
Attribute `_value` not initialized in the class `Node` though it has corresponding `value` property setter and getter by default and available to it and its derived classes, causing errors like the following when accessed:

> AttributeError: 'Stream' object has no attribute '_value'

https://github.com/tensortrade-org/tensortrade/blob/401062089d4235eb844c588b3ff4a841cdc30b43/tensortrade/data/stream/node.py#L45-L51

**Comment by mwbrulhardt** [comment]
What is the context in which you have run this?

**Comment by YasserHassan** [comment]
I was following the `train_and_evaluate.ipynb` tutorial and wanted to investigate `Stream` more so I created a stream object separately, something like
`stream = Stream("USD-BTC", list(coinbase_data['BTC:close']))`
then tried to print `stream.value` and received that error.

**Comment by mwbrulhardt** [comment]
A `Node` can only exist within the context of a data feed. So if the data feed has not been compiled, then no nodes will not have values. The reason why it works this way is because the `DataFeed` system is a directed acyclic graph and it needs to first correctly set the order for all the nodes to run in, so that every node performs computation with the correct value.

**Comment by YasserHassan** [comment]
That needs to be clarified in the documentation to avoid creating similar issue in the future.
