### ISSUE TITLE
Enhancement: Rename 'locked' in Wallet to 'reserved' for clarity

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#207]
The concept of locked balance in `Wallet` is not sitting well with me. In reality, once money gets out of a wallet it becomes "spent" money. We don't reserve a placeholder or register that in the wallet. "Locked" implies that this value is expected to be freed later which is not always the case. The value may never return from the form it was converted into. For example, when purchasing shares in a company that goes bankrupt later, those shares are lost forever.

Moreover, when the process is reversed and the purchased asset is sold, its value will almost always change so when that value is returned to the original wallet, the corresponding locked value will not be satisfied. So there will always be a difference leaving another locked value portion hanging as a surplus or deficit.

If the reason is to keep track of values moving between wallets inside a single portfolio then this is the role of a ledger attached to the portfolio. So I think the role of the wallet should be only to hold information about what's available at a certain time and there's no place for locked values.

**Comment by mwbrulhardt** [comment]
There is no concept locked balance necessarily in any functional sense. A locked balance is a summary statistic about the wallet looking over all orders that are currently involved with it. The concept of locked quantities in an `Order` is where the use of locking comes in handy. Here are some of the reasons why we use locked quantities:

- If an order is not a simple buy and sell, then funds must be allocated such that there is assurance of the order carrying out its full lifetime. 
    - Given:
        - `w1 = Wallet(10000, USD)`
        - `w2 = Wallet(0, BTC)`
        - `o1 = LimitOrder(size=9,350 USD, side=buy, limit_price=9,350 USD/BTC)`
        - `o2 = Order(size=2000 USD, price=9,400 USD/BTC, side=buy)`
    - For example, say an order `o1` is submitted to the `Broker`. This order will only be triggered when the criteria is satisfied of the price being less than or equal to `9,350 USD/BTC` . Then if at the next time step an order `o2` is submitted there becomes a conflict over funds. Should the order 'o2' be able to execute even if `o1` has not completed its lifetime? If `o2` executes then there will be no funds left for `o1` and the order will be cancelled. We have decided that the best course of action to solve this problem is to not let the order `o2` happen in the first place. If funds are locked (set aside/ allocated for) `o1`, then we have a guarantee that `o1` can play out its life cycle without any interruption. The only way it can be halted is if explicitly cancelled. 


-  For orders such as `take profit/stop loss`, which are  multi-step orders, funds must be allocated for these orders and tracked through wallet transitions such that it will not be tampered by any other orders being made in the system. You need a quantity to always be associated with this mulit-step transition, hence the locked quantities. This guarantees that these orders will be able to play out their full life cycle.

So the locked balance of a wallet is simply a summary statistic over orders currently situated at that wallet to tell us the amount of funds that are currently locked in an order. As for your last point, we can already manage what transactions are happening in a wallet by the methods that are currently built into the wallet, however, that is not the point of locked quantities and the ledger would not solve our problem.

Locked quantities are the backbone of the order management system so if that is something you would want changed then you would need to propose a completely new order management system.  The system would have to give substantial benefits over the one currently implemented in order to initiate a change this large.

**Comment by YasserHassan** [comment]
This is a different use from what I understood from the variable name `locked` and how it seemed on the performance chart. It makes sense now.

But I suggest changing that name though to "reserved" which is a more expressive and intuitive name for this role. "locked" could be for before or after a transaction. "reserved" is clearly for a transaction that yet to take place.

**Comment by spacewalkingninja** [comment]
> For example, when purchasing shares in a company that goes bankrupt later, those shares are lost forever.

@YasserHassan I think the solution would be easier if the bot should not buy shares or currency or anything that depreciates in value. This way it can be locked untill it makes a profit from that buy?

**Comment by YasserHassan** [comment]
@spacewalkingninja after @mwbrulhardt's explanation, I see that the function of locked/reserved values makes sense and even required for proper order management.

I believe the solution your proposed is not possible. How will you manage to identify instruments that depreciate in value to avoid buying them? (that means you know how to never lose money!). The current approach is good and safe. It just needs name change.

**Comment by spacewalkingninja** [comment]
> @spacewalkingninja after @mwbrulhardt's explanation, I see that the function of locked/reserved values makes sense and even required for proper order management.
> 
> I believe the solution your proposed is not possible. How will you manage to identify instruments that depreciate in value to avoid buying them? (that means you know how to never lose money!). The current approach is good and safe. It just needs name change.

Well, it would be logical to do this if we intent to make money with this... Why'd you buy something that deppreciates in the first place? Unless it has some hidden Future Forecasting function we haven't discovered yet that makes it buy and then hold onto the asset. Not sure... imo, it should be something like:
python tensortrade.py -apiKey -wallet -howMuchMoneyToSpend -howMuchMoneyToWin

**Comment by YasserHassan** [comment]
It's not the matter of logic, it just can not be done. If you discovered how to avoid buying instrument that depreciate in price (that is, on the flip side, how to pick winning trades only) then you have discovered the holy grail of trading that every one is after. And you wouldn't need this framework to start with.

With @mwbrulhardt's explanation, this has become a minor issue that can be handled by proper documentation instead (still better via code) so I'll close it.
