### ISSUE TITLE
Duplicate entries in performance dataframe

### ISSUE THREAD

**Issue by andy121090** [tensortrade-org/tensortrade#233]
In the example `train_and_evaluate.ipynb` the total reward is always constant and equal to `3.0`.

The issue seems to be that the function `on_next` of portfolio is called twice when `env.feed.next()` is executed.

**System information**

- Have I written custom code (as opposed to using example directory): no
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): Linux
- TensorTrade version: 0.2.0-beta.2
- TensorFlow version: 2.1.0
- Python version: 3.6.9

**Describe the current behavior**
Total reward in the mentioned example is always constant.

**Describe the expected behavior**
Total reward should vary.

**Code to reproduce the issue**  
Example `train_and_evaluate.ipynb` with a little bit modified line:
```
agent.train(n_steps=200, save_path="examples/agents/", n_episodes=3)
```

**Comment by UncleVasya** [comment]
Can confirm. Every row in `portfolio.performance` is recorded twice:

![](https://i.imgur.com/lTdf4Lz.png)

#### Consequences

In our reward functions we calculate percentage change of `performance.net_worth`:

`returns = portfolio.performance['net_worth'][-(self._window_size + 1):].pct_change().dropna()`

Because of duplicated values percentage change is always 0 (with default `window_size=1`.) And rewards are totally wrong.

#### Cause

Data stream listener gets called twice:

1. from `DataFeed.nex()`
2. from `DataFeed.next() -> DataFeed.run() -> super(DataFeed).run() = Node.run()`

Because `DataFeed` in a subclass of `Node`

#### Possible solution

There is no need to call listeners in `DataFeed.next()` because they will be called by superclass `Node` anyway.

Remove 

```
for listener in self.listeners:
    listener.on_next(self.value)
```
from `DataFeed.next()`

**Comment by kodiakcrypto** [comment]
fixed it on my fork
thanks

**Comment by GolemXlV** [comment]
Have you test it? In my case, after comment this lines in feed.py, i have a problems with order execution (all orders have a state locked).

**Comment by mwbrulhardt** [comment]
I've solved this in the `environment-refactor` branch thanks for letting us know!
