### ISSUE TITLE
Question on Exchanges and Stocks

### ISSUE THREAD

**Issue by Rockyyost** [tensortrade-org/tensortrade#282]
How would you use the Exchange modules for stocks? Looks like things more focused on currency pairs at the moment. 

Thanks!

**Comment by patrick-bercow** [comment]
same question,is it possible to have a refactor to support future exchange?

**Comment by carlogrisetti** [comment]
Actually the exchange is merely the entity (company) that provides you exchange services, between your base asset (that can be a currency like USD, or it can also be any other type of asset), and the assets you want to trade.
Different exchanges can have different transaction costs and different assets available to trade, so that's the reasoning behind this structure.

Once you have an exchange set up, you can define two wallets, one with USD and another with any other asset you like (might be a stock, might be a commodity or anything else), and build a portfolio comprising both those elements, like:


`USD = Instrument("USD", 2, "U.S. Dollar")`
`AAPL = Instrument("AAPL", 2, "Apple Inc.")`
`cash = Wallet(eToro_exchange, 10000 * USD)`
`asset = Wallet(eToro_exchange, 0 * AAPL)`
`portfolio = Portfolio(USD, [cash, asset])`

Is that what you meant?

**Comment by carlogrisetti** [comment]
> same question,is it possible to have a refactor to support future exchange?

@patrick-bercow You can work around it by treating the future as a normal asset. I know it's not the same thing, but I don't see why it shouldn't work if you treat the future as a generic object, without considering the date, as per the example above. In any other consideration, it's not implemented, and probably won't be in the near future (I think, and it's my personal opinion, that the next implementation could be positions with shorts)

**Comment by bergen288** [comment]
@carlogrisetti 
How do define ```eToro_exchange``` in your example above?  Is there a predefined Exchange for stocks?

**Comment by carlogrisetti** [comment]
Damn I completely missed this question. Take a look at the latest example. It's not any sort of "integration" as you might think. It's only the name I assigned to that exchange object. In the example you'll see that written as
`ttse_exchange = Exchange("TTSE", service=execute_order, options=ttse_options)(price)`
https://www.tensortrade.org/en/latest/examples/train_and_evaluate_using_ray.html

Closing due to being obsolele. If there are any other unrelated comments please open a new issue to keep things tidy :)
