### ISSUE TITLE
Feature Request: Support for Shorting

### ISSUE THREAD

**Issue by eicnix** [tensortrade-org/tensortrade#317]
To further improve the usefulness of TensorTrade in real world applications I would like to short an instrument as part of a strategy. 

From a user perspective I would like to create a sell order on an instrument without any net worth to receive a negative balance.

**Comment by TraderWithPython** [comment]
I think so

**Comment by carlogrisetti** [comment]
This is not just as simple as enabling it to have a negative balance, but implementing a new action space, and new actions in the environment.
It is not currently supported, nor we plan on adding it in the near time, but you are more than free to submit a PR implementing this if you feel so and are capable

Thanks for the suggestion anyway!

**Comment by ddragosd** [comment]
I need this too. Happy to make a PR if we can agree on implementation. I like the _negative balance_ idea in a wallet as that's communicating quite clearly what happened (negative balance == shorting). I would assume the _Exchange_ would be responsible for implementing the shorting. What it's not clear is how much the agent should be allowed to _borrow_.  

It's also illegal to [short against the box](https://www.investopedia.com/terms/s/sellagainstthebox.asp) from what I gathered. I think this makes the implementation simpler because we don't need to keep a wallet with both positive and negative balanced of the same symbol.
