### ISSUE TITLE
short trades, down trend and wallet with negative value

### ISSUE THREAD

**Issue by mvccn** [tensortrade-org/tensortrade#327]
Is there any easy way to model short trade in the current framework? Wallet can't hold negative value, it will give InvalidNegativeQuantity exception.  However, this is needed if we want to have a short position. The BSH action scheme can only have all cash or all asset, which can't take advantage the down trend. I think a action scheme which can have cash(netrual), positive asset(long), negative asset(short), will help a lot in modeling real life scenarios.

**Comment by mablue** [comment]
yes its possable cuz its opensource .:)

**Comment by carlogrisetti** [comment]
What you want is not just to have "sell" meaning that you sell assets you have or short assets you don't have, but you need 4 actions:
Long Buy (ie: the current "buy")
Long Sell (ie: the current "seell")
Short Sell
Short Buy (closing\covering the short position taken)
Hold is just having the same action as the last time, so it's a "logical" action, not a model output per se.

The weird thing would also be to manage transitions like: T+1 I am long buying AAPL, T+2 I am short selling AAPL.
Does this mean that I also have to implicitly long sell AAPL? I think so.
Do they need to be separate actions? Sure, because you could just Long Sell because it's not confident in a rise in price, but since it's not confident in a drop in price also, the best bet would be to wait it out and not open a Short Sell.

It's a little bit complicated to sort all those dynamics out and choose the best way to implement it, but hey... if anyone's willing to help by submitting a PR, it could be done.

I myself have no interest in that, since I am basically against short selling as a concept, and do not want to tackle that in my trading, but many others are!

(closing this issue in the meantime, since it's gone stale)
